apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webserver
    role: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:alpine
    ports:
    - containerPort: 80